# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-24 19:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abstract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('abstract_text', models.TextField()),
                ('upload_datetime', models.DateTimeField()),
            ],
            options={
                'ordering': ('-upload_datetime',),
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('affiliation', models.TextField()),
                ('abstract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Abstract')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
