# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-25 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20171124_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='affiliation',
            field=models.CharField(max_length=1000),
        ),
    ]
